config/routes.rb
Rails.application.routes.draw do
  resources :cities

  resources :states do
    member do
      get :cities
    end
  end

  resources :countries do
    member do
      get :states
    end
  end

  

  root :to => 'countries#index'
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :state
  has_one  :wiki_link, as: :linkable

  validates :name, presence: true
  validates :population, numericality: true
  validates :area, numericality: true
  validates :state_id, presence: true

end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :states, dependent: :destroy
  has_one  :wiki_link, as: :linkable

  validates :name, presence: true
  validates :currency, presence: true
  validates :timezone, presence: true

  def area
    area = 0
    self.states.each do|state|
      area += state.area
    end
    return area
  end

  def literacy
    sum = 0
    self.states.each do|state|
      sum += state.literacy
    end
    if self.states.count == 0
      return sum
    else
      return (sum/self.states.count)
    end
  end

  def population
    population = 0
    self.states.each do|state|
      population += state.population
    end
    return population
  end
end

app/models/state.rb
class State < ActiveRecord::Base
  belongs_to :country
  has_many :cities, dependent: :destroy
  has_one  :wiki_link, as: :linkable

  validates :name, presence: true
  validates :literacy, presence: true, numericality: true
  validates :country_id, presence: true

  def area
    area = 0
    self.cities.each do|city|
      area += city.area
    end
    return area
  end

  def population
    population = 0
    self.cities.each do|city|
      population += city.population
    end
    return population
  end

end

app/models/wiki_link.rb
class WikiLink < ActiveRecord::Base
  belongs_to :linkable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout "layouts/default"
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_filter :initialize_presenter_manager

  def new
    @city = City.new
  end

  def create
    @city = City.new(city_params)
    @city.save
    respond_to do |format|
      format.html { redirect_to cities_state_path(@city.state_id) }
      format.json { head :no_content }
    end
  end

  def destroy
    @city = City.find(params[:id])
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_state_path(@city.state_id) }
      format.json { head :no_content }
    end
  end

  private
    def initialize_presenter_manager
      @manager = Manager.new
      @presenter = Presenter.new
    end
    
    def city_params
      params.require(:city).permit(:name, :population, :area, :state_id)
    end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_filter :initialize_presenter_manager

  def index
    @countries = Country.all
    @country = Country.new
    @columns_headers = @manager.country_datatable_columns

    respond_to do |format|
      format.html
      format.json do
        countries_data = @manager.prepare_countries_data(@countries)
        countries_data_json = @presenter.format_countries_data(countries_data)
        render :json => @presenter.generate_datatable_json(params, countries_data_json, countries_data.count)
      end
    end
  end

  def states
    @state = State.new
    @country = Country.includes(states: [:cities]).find(params[:id])
    states = State.where(country_id: @country.id)
    @columns_headers = @manager.state_datatable_columns
    
    respond_to do |format|
      format.html {render :template => '/countries/show_states'}
      format.json do 
        states_data = @manager.prepare_states_data(states)
        states_data_json = @presenter.format_states_data(states_data)
        render :json => @presenter.generate_datatable_json(params, states_data_json, states_data.count)
      end
    end
  end

  def create
    @country = Country.new(country_params)
    @country.save
    respond_to do |format|
      format.html { redirect_to :action => "index"}
      format.json { redirect_to :action => "index"}
    end
  end

  def destroy
    @country = Country.find(params[:id])
    @country.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  private
    def initialize_presenter_manager
      @manager = Manager.new
      @presenter = Presenter.new
    end

    def country_params
      params.require(:country).permit(:name, :currency, :timezone)
    end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :initialize_presenter_manager

  def cities
    @state = State.includes(:cities,:wiki_link).find(params[:id])
    @city = City.new
    @columns_headers = @manager.city_datatable_columns
    respond_to do |format|
      format.html {render :template => '/states/show_cities'}
      format.json do 
        cities_data = @manager.prepare_cities_data(@state.cities)
        cities_data_json = @presenter.format_cities_data(cities_data)
        render :json => @presenter.generate_datatable_json(params, cities_data_json, cities_data.count)
      end
    end
  end

  def create
    @state = State.new(state_params)
    @state.save
    respond_to do |format|
      format.html { redirect_to states_country_path(@state.country_id)}
      format.json { redirect_to states_country}
    end
  end

  def destroy
    @state = State.find(params[:id])
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_country_path(@state.country_id) }
      format.json { head :no_content }
    end
  end

  private
    def initialize_presenter_manager
      @manager = Manager.new
      @presenter = Presenter.new
    end

    def state_params
      params.require(:state).permit(:name, :literacy, :country_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/countries/_form_country.html.erb
<%= form_for(@country) do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :currency %><br>
    <%= f.text_field :currency %>
  </div>
  <div class="field">
    <%= f.label :timezone %><br>
    <%= f.text_field :timezone %>
  </div>
  <div class="actions modal-footer">
    <%= f.submit %>
  </div>
<% end %>

app/views/countries/_form_state.html.erb
<%= form_for(@state) do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :literacy %><br>
    <%= f.text_field :literacy %>
  </div>
  <div class="field">
    <%= f.label :country_id %><br>
    <% options = options_from_collection_for_select(Country.all(), 'id', 'name') %>
    <%= f.select :country_id, options %>
  </div>
  <div class="actions modal-footer">
    <%= f.submit %>
  </div>
<% end %>

app/views/countries/index.html.erb
<h1>Listing countries</h1>
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">New Country</button>

<table id="countries_list" cellpadding="0" cellspacing="0" border="0" class=" table table-striped table-bordered" data-url="<%= countries_path%>">
  <thead>
    <tr>
      <%= @presenter.display_column_headers(@columns_headers) %>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New Country</h4>
      </div>
      <div class="modal-body">
        <%= render partial: "form_country" %>
      </div>
    </div>
  </div>
</div>

app/views/countries/show_states.html.erb
<h1>Listing States in <%= @country.name%></h1>
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">New State</button>

<table id="country_states_list" cellpadding="0" cellspacing="0" border="0" class="datatable table table-striped table-bordered" data-url="<%= states_country_path(@country.id)%>">
  <thead>
    <tr>
      <%= @presenter.display_column_headers(@columns_headers) %>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"> New State</h4>
      </div>
      <div class="modal-body">
        <%= render partial: "form_state" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/default.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Myapp" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="container">
      <%= yield %>
      <footer>
        <p>Copyright@2015</p>
      </footer>
    </div>
  </body>
</html>

app/views/states/_form_city.html.erb
<%= form_for(@city) do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :population %><br>
    <%= f.text_field :population %>
  </div>
  <div class="field">
    <%= f.label :area %><br>
    <%= f.text_field :area %>
  </div>
  <div class="field">
    <%= f.label :state_id %><br>
    <% options = options_from_collection_for_select(State.all(), 'id', 'name') %>
    <%= f.select :state_id, options %>
  </div>
  <div class="actions modal-footer">
    <%= f.submit %>
  </div>
<% end %>

app/views/states/show_cities.html.erb
<h1>Listing Cities in <%= @state.name%></h1>
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">New City</button>

<table id="state_cities_list" cellpadding="0" cellspacing="0" border="0" class="datatable table table-striped table-bordered" data-url="<%= cities_state_path(@state.id)%>">
  <thead>
    <tr>
      <%= @presenter.display_column_headers(@columns_headers) %>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New City</h4>
      </div>
      <div class="modal-body">
        <%= render partial: "form_city" %>
      </div>
    </div>
  </div>
</div>